name: Run Carwow Valuation Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'  # runs daily at 6am UK time

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          - name: Install Playwright with system dependencies
  run: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    sudo apt-get update
    sudo apt-get install -y libasound2 libxss1 libnss3 libatk-bridge2.0-0 libgtk-3-0 libx11-xcb1 libxcb-dri3-0 libdrm2 libgbm1 libxcomposite1 libxrandr2 libxdamage1 libxext6 libxfixes3 libxkbcommon0
    python -m playwright install


      - name: Run Carwow Valuation
        env:
          GOOGLE_CREDS_JSON: ${{ secrets.GOOGLE_CREDS_JSON }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
        run: python carwow_valuation_bot.py

